name: Trigger auto deployment for crud-sample-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/crud-sample-app-AutoDeployTrigger-41da6b68-728d-4b19-89fe-1c10725e83cd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gtgithubcopilot.azurecr.io
          username: ${{ secrets.CRUDSAMPLEAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.CRUDSAMPLEAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gtgithubcopilot.azurecr.io/dcom-demo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CRUDSAMPLEAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n crud-sample-app -g DCOM-Demo --server gtgithubcopilot.azurecr.io --username  ${{ secrets.CRUDSAMPLEAPP_REGISTRY_USERNAME }} --password ${{ secrets.CRUDSAMPLEAPP_REGISTRY_PASSWORD }}
            az containerapp update -n crud-sample-app -g DCOM-Demo --image gtgithubcopilot.azurecr.io/dcom-demo:${{ github.sha }}
